# Generated by Django 4.1.3 on 2022-12-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='users/cover_photos/default.jpg', null=True, upload_to='users/cover_photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/profile_pictures/default.jpg', null=True, upload_to='users/profile_pictures'),
        ),
    ]
